library(e1071)
library(car)
ComputerData <- read.csv(file.choose())

ComputerData <- ComputerData[,-1]

attach(ComputerData)

# First Moment Business Decision
summary(ComputerData)
# Second Moment Business Decision
sd(price)
sd(speed)
sd(hd)
sd(ram)
sd(screen)
sd(ads)
sd(trend)
plot(speed, price)
plot(hd, price)
plot(ram, price)
plot(screen, price)
plot(ads, price)
plot(trend, price)
plot(cd, price)
plot(multi, price)
plot(premium, price)
pairs(ComputerData)
model <- lm(price ~ speed + hd + ram + screen + ads + trend + cd + multi + premium, data = ComputerData)
summary(model)
model2 <- lm(price ~ ., data = ComputerData[-c(1441, 1701),])
summary(model2)
vif(model2)
avPlots(model2)
model3 <- lm(price ~ speed + hd + ram + screen + ads + trend + premium, data = ComputerData[-c(1441, 1701),])
summary(model3)
avPlots(model3)
plot(model)
qqPlot(model)
