Corolla <- read.csv(file.choose())
View(Corolla)
attach(Corolla)
Corolla_Pred <- cbind(Price,Age_08_04,KM,HP,cc,Doors,Gears,Quarterly_Tax,Weight)
Corolla_Pred1 <- as.data.frame(Corolla_Pred)
class(Corolla_Pred1)
View(Corolla_Pred1)
attach(Corolla_Pred1)
summary(Corolla_Pred1)
plot(Age_08_04, Price)
plot(KM, Price)
plot(HP, Price)
plot(cc, Price)
plot(Doors, Price)
plot(Gears, Price)
plot(Quarterly_Tax, Price)
plot(Weight, Price)
windows()
pairs(Corolla_Pred1)
cor(Corolla_Pred1)
corolla.price <- lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight)
summary(corolla.price)
corolla.price2 <-lm(Price~Age_08_04+KM+HP+Gears+Quarterly_Tax+Weight)
summary(corolla.price2)
pairs(Corolla_Pred1)
library(corpcor)
cor2pcor(cor(Corolla_Pred1))
library(mvinfluence)
library(car)
influence.measures(corolla.price)
influenceIndexPlot(corolla.price, id.n=3)
corolla.price1 <- lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight,data=Corolla_Pred1[-81,])
summary(corolla.price1)
vif(corolla.price1)
layout(matrix(c(1,2,3,4),2,2))
plot(corolla.price1)
finalmodel <- lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight)
summary(finalmodel)
Price_Predict <- predict(corolla.price,interval="predict")
Pred_final <- predict(corolla.price)
Final <- cbind(Price,Pred_final,Age_08_04,KM,HP,cc,Doors,Gears,Quarterly_Tax,Weight)
View(Final)
