data_cal_wt <- read.csv(file.choose())
View(data_cal_wt)
attach(data_cal_wt)
plot(data_cal_wt)
summary(data_cal_wt)
cor(Weight.gained..grams.,Calories.Consumed)
reg <- lm(Weight.gained..grams.~ Calories.Consumed)
summary(reg)
confint(reg,level=0.95)
predict(reg,interval="predict")
# transform
reg_sqrt <- lm(Weight.gained..grams.~ sqrt(Calories.Consumed))
summary(reg_sqrt)
confint(reg_sqrt,level=0.95)
predict(reg_sqrt,interval="predict")
# transform
reg_log1 <- lm(Weight.gained..grams.~ log(Calories.Consumed))
summary(reg_log1)
confint(reg_log1,level=0.95)
predict(reg_log1,interval="predict")
# transform
reg_exp1 <- lm(log(Weight.gained..grams.)~ Calories.Consumed)
summary(reg_exp1)
confint(reg_exp1,level=0.95)
predict(reg_exp1,interval="predict")
